-- The MCP server authorizes with OAuth, not API keys. The web app is the
-- authorization server: a client identifies itself by the URL of its
-- metadata document or by a pre-registered client_id, the user consents, and
-- the MCP server accepts the short access token signed with the keys of
-- auth_jwks. The tables are generated by `npx auth generate` from
-- packages/core/src/auth.ts, unchanged.
--
-- Better Auth does not write auth_account.issuer: left NOT NULL, the column
-- fails every sign-up, and its unique index on (issuer, accountId) guards
-- nothing. Relaxed rather than dropped, as Better Auth's upgrade guide
-- prescribes.
alter table "auth_account" alter column "issuer" drop not null;
drop index "auth_account_issuer_accountId_uidx";

-- An API key opens nothing anymore: the table goes with the plugin.
drop table "auth_apikey";

create table "auth_jwks" ("id" text not null primary key, "publicKey" text not null, "privateKey" text not null, "createdAt" timestamptz not null, "expiresAt" timestamptz, "alg" text, "crv" text);

create table "auth_oauth_client" ("id" text not null primary key, "clientId" text not null unique, "clientSecret" text, "clientDiscoveryId" text, "disabled" boolean, "skipConsent" boolean, "enableEndSession" boolean, "subjectType" text, "scopes" jsonb, "clientCredentialsScopes" jsonb, "userId" text references "auth_user" ("id") on delete cascade, "createdAt" timestamptz, "updatedAt" timestamptz, "name" text, "uri" text, "icon" text, "contacts" jsonb, "tos" text, "policy" text, "softwareId" text, "softwareVersion" text, "softwareStatement" text, "redirectUris" jsonb not null, "postLogoutRedirectUris" jsonb, "backchannelLogoutUri" text, "backchannelLogoutSessionRequired" boolean, "tokenEndpointAuthMethod" text, "applicationType" text, "jwks" text, "jwksUri" text, "grantTypes" jsonb, "responseTypes" jsonb, "requirePKCE" boolean, "dpopBoundAccessTokens" boolean, "referenceId" text, "metadata" jsonb);

create table "auth_oauth_resource" ("id" text not null primary key, "identifier" text not null unique, "name" text not null, "accessTokenTtl" integer, "refreshTokenTtl" integer, "signingAlgorithm" text, "signingKeyId" text, "allowedScopes" jsonb, "customClaims" jsonb, "dpopBoundAccessTokensRequired" boolean, "disabled" boolean, "createdAt" timestamptz, "updatedAt" timestamptz, "policyVersion" integer, "metadata" jsonb);

create table "auth_oauth_client_resource" ("id" text not null primary key, "clientId" text not null references "auth_oauth_client" ("clientId") on delete cascade, "resourceId" text not null references "auth_oauth_resource" ("identifier") on delete cascade, "metadata" jsonb, "createdAt" timestamptz);

create table "auth_oauth_refresh_token" ("id" text not null primary key, "token" text not null unique, "clientId" text not null references "auth_oauth_client" ("clientId") on delete cascade, "sessionId" text references "auth_session" ("id") on delete set null, "userId" text not null references "auth_user" ("id") on delete cascade, "referenceId" text, "authorizationCodeId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "rotatedAt" timestamptz, "rotationReplayResponse" text, "rotationReplayExpiresAt" timestamptz, "authTime" timestamptz, "confirmation" jsonb, "scopes" jsonb not null);

create table "auth_oauth_access_token" ("id" text not null primary key, "token" text not null unique, "clientId" text not null references "auth_oauth_client" ("clientId") on delete cascade, "sessionId" text references "auth_session" ("id") on delete set null, "userId" text references "auth_user" ("id") on delete cascade, "referenceId" text, "authorizationCodeId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "refreshId" text references "auth_oauth_refresh_token" ("id") on delete cascade, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "confirmation" jsonb, "scopes" jsonb not null);

create table "auth_oauth_consent" ("id" text not null primary key, "clientId" text not null references "auth_oauth_client" ("clientId") on delete cascade, "userId" text references "auth_user" ("id") on delete cascade, "referenceId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "scopes" jsonb not null, "createdAt" timestamptz not null, "updatedAt" timestamptz not null);

create table "auth_oauth_client_assertion" ("id" text not null primary key, "expiresAt" timestamptz not null);

create index "auth_oauth_client_userId_idx" on "auth_oauth_client" ("userId");

create index "auth_oauth_client_resource_clientId_idx" on "auth_oauth_client_resource" ("clientId");

create index "auth_oauth_client_resource_resourceId_idx" on "auth_oauth_client_resource" ("resourceId");

create index "auth_oauth_refresh_token_clientId_idx" on "auth_oauth_refresh_token" ("clientId");

create index "auth_oauth_refresh_token_sessionId_idx" on "auth_oauth_refresh_token" ("sessionId");

create index "auth_oauth_refresh_token_userId_idx" on "auth_oauth_refresh_token" ("userId");

create index "auth_oauth_refresh_token_authorizationCodeId_idx" on "auth_oauth_refresh_token" ("authorizationCodeId");

create index "auth_oauth_access_token_clientId_idx" on "auth_oauth_access_token" ("clientId");

create index "auth_oauth_access_token_sessionId_idx" on "auth_oauth_access_token" ("sessionId");

create index "auth_oauth_access_token_userId_idx" on "auth_oauth_access_token" ("userId");

create index "auth_oauth_access_token_authorizationCodeId_idx" on "auth_oauth_access_token" ("authorizationCodeId");

create index "auth_oauth_access_token_refreshId_idx" on "auth_oauth_access_token" ("refreshId");

create index "auth_oauth_consent_clientId_idx" on "auth_oauth_consent" ("clientId");

create index "auth_oauth_consent_userId_idx" on "auth_oauth_consent" ("userId");

create unique index "auth_oauth_client_resource_clientId_resourceId_uidx" on "auth_oauth_client_resource" ("clientId", "resourceId");