/**
 * What a refused gesture says to the person in front of the screen. The domain
 * throws a code and an English sentence for the log; this is where that code
 * becomes French, once, for every action of the app.
 *
 * A code with no line here falls back to the domain's own message, which is
 * readable but written for whoever reads the code: a gesture the interface
 * offers deserves a sentence written for its user, and a test holds that line.
 */
export const FR: Record<string, string> = {
  account_closed:
    'Ce compte est clos : une activité ne se met pas à vivre dessus, et rien ne s’y déclare après.',
  transfer_has_no_category: 'Un virement interne ne porte pas de catégorie.',
  not_an_advance: 'Le mouvement visé n’est pas une avance.',
  financing_settled: 'Ce financement est déjà soldé.',
  not_a_financing: 'Seul un financement porte un échéancier écrit.',
  schedule_empty: 'Un financement garde au moins une échéance : clos-le plutôt que de vider son plan.',
  installment_not_found: 'Une échéance de ce plan n’existe plus : rouvre le panneau pour repartir à jour.',
  installment_repeated: 'La même échéance apparaît deux fois dans le plan.',
  commitment_not_found: 'Cet engagement n’existe plus.',
  cancelled: 'Cet engagement est résilié.',
  already_cancelled: 'Cet engagement est déjà résilié.',
  no_gap: 'Ce pointage n’a aucun écart à solder.',
  actor_exists: 'Ce nom désigne déjà un acteur existant.',
  bad_source: 'Il manque le compte ou l’acteur source.',
  bad_target: 'Il manque le compte ou l’acteur destination.',
  no_owned_account: 'Un mouvement doit toucher au moins un de tes comptes.',
  movement_not_found: 'Ce mouvement n’existe plus.',
  refunded_movement: 'Un remboursement est lié à ce mouvement : supprime d’abord le remboursement.',
  account_exists: 'Un compte porte déjà ce nom.',
  account_not_found: 'Ce compte n’existe plus.',
  account_has_operations:
    'Ce compte porte des opérations d’investissement : son type ne change plus. Le reste se corrige.',
  opening_needs_its_day: 'Indique le jour d’ouverture : c’est à partir de là que ce solde compte.',
  actor_not_found: 'Cet acteur n’existe plus.',
  actor_has_no_activity: 'Attache d’abord une activité à cet acteur.',
  category_exists: 'Une catégorie porte déjà ce nom.',
  category_not_found: 'Cette catégorie n’existe plus.',
  activity_exists: 'Une activité porte déjà ce nom.',
  activity_not_found: 'Cette activité n’existe plus.',
  activity_closed: 'Cette activité est close à cette date.',
  activity_regime_fixed:
    'Cette activité porte des règles ou des factures : elle ne change pas de régime. Clos-la et crée la suivante.',
  activity_has_accounts: 'Cette activité vit sur des comptes : retire-les d’abord de sa fiche.',
  activity_not_business:
    'Seule une activité indépendante vit sur des comptes, et porte factures, règles et seuils.',
  vat_rate_needs_registration: 'Un taux de TVA suppose une activité assujettie.',
  activity_closes_before_start: 'La clôture précède le début de l’activité.',
  jurisdiction_not_found: 'Cette juridiction n’est plus au catalogue : reprends la première étape.',
  regime_model_not_found: 'Ce régime n’est plus au catalogue : reprends le questionnaire.',
  regime_answer_unknown: 'Une réponse ne correspond à aucune option : reprends le questionnaire.',
  regime_answers_incomplete: 'Une question est restée sans réponse : reprends le questionnaire.',
  regime_model_excluded: 'Tes réponses écartent ce régime : reprends le questionnaire.',
  bad_rate: 'Un taux est un pourcentage entre 0 et 100.',
  check_not_found: 'Ce pointage n’existe plus.',
  check_already_settled: 'Un ajustement solde déjà ce pointage.',
  financing_has_no_lock_in: 'Un financement s’arrête à sa dernière échéance : pas de date de fin.',
  alias_taken: 'Ce nom désigne déjà un acteur : fusionne-les plutôt que d’ajouter cet alias.',
  merge_self: 'Un acteur ne se fusionne pas avec lui-même.',
  advance_needs_amount: 'Indique la part attendue en remboursement.',
  advance_needs_actor: 'Indique qui doit rembourser cette part.',
  advance_amount_invalid: 'La part attendue doit être supérieure à zéro.',
  advance_amount_too_large: 'La part attendue ne peut pas dépasser le montant de la dépense.',
  advance_is_expense: 'Seule une dépense peut être avancée pour quelqu’un.',
  advance_has_refund:
    'Un remboursement est déjà lié à cette avance : supprime-le avant de retirer la créance.',
  advance_below_refunds: 'La part attendue est déjà dépassée par ce qui a été remboursé.',
  advance_settled: 'Cette avance est déjà remboursée en entier.',
  transfer_stays_eur: 'Un virement entre tes comptes se déclare en euros.',
  transfer_has_no_accrual: 'Un virement interne n’entre dans aucun total de période : pas de rattachement.',
  transfer_has_no_vat: 'Un virement interne ne porte pas de TVA.',
  vat_outside_amount: 'La TVA est comprise dans le montant : elle ne peut pas le dépasser.',
  vat_needs_registered_activity:
    'Seule une dépense d’une activité indépendante assujettie porte une TVA déductible.',
  bad_month: 'Ce mois est invalide.',
  needless_eur_amount: 'Le montant est déjà en euros : la contre-valeur ne s’applique pas.',
  no_exchange_rate:
    'Aucun cours connu pour cette devise à cette date. Vérifie le code, ou saisis les euros débités.',
  bad_currency: 'Une devise est un code ISO à trois lettres, autre que EUR.',
  financing_keeps_currency:
    'L’échéancier d’un financement est écrit dans sa devise : clos-le et déclare le nouveau plan.',
  not_an_investment_account:
    'Seul un compte d’investissement porte des opérations. Alimenter ce compte est un virement.',
  operation_not_found: 'Cette opération n’existe plus.',
  asset_is_quoted: 'Cet actif prend son cours à sa source : un cours saisi ferait double emploi.',
  asset_has_operations:
    'Cet actif porte des opérations : elles font l’histoire du compte. Supprime-les d’abord, ou garde-le.',
  oversold: 'Tu vends plus que ce compte détient. Vérifie la quantité, et le compte.',
  needs_quantity:
    'Indique la quantité achetée, telle que le courtier l’affiche : le cours d’exécution seul peut la dire.',
  needs_asset: 'Indique l’actif concerné.',
  same_account: 'Un versement va d’un compte vers un autre : ces deux-là sont le même.',
  placement_has_no_actor:
    'Un versement programmé ne paie personne : ni acteur, ni catégorie, ni date de fin d’engagement.',
  not_a_placement: 'Seul un versement programmé alimente un compte d’investissement et achète un actif.',
  asset_has_plans: 'Un versement programmé achète cet actif : arrête le versement d’abord, ou garde l’actif.',
  asset_exists: 'Ce nom est pris, ou tu détiens déjà cet instrument sous un autre nom.',
  asset_not_found: 'Cet actif n’existe plus.',
  levy_not_found: 'Cette règle n’existe plus.',
  levy_has_no_settlement_category:
    'Cette règle ne dit pas où ses règlements se classent : donne-lui une catégorie de règlement dans Réglages.',
  levy_validity: 'La fin de validité tombe avant le début.',
  levy_form_needs_param: 'Cette forme de montant a besoin de son paramètre.',
  levy_form_param_unexpected: 'Un paramètre d’une autre forme de montant a été envoyé.',
  levy_params_invalid: 'Un paramètre structuré est invalide.',
  levy_value_invalid: 'Une valeur saisie est hors de ses bornes.',
  levy_base_needs_levy: 'Cette mesure lit une autre règle : indique laquelle.',
  levy_base_needs_input: 'Cette mesure lit un paramètre saisi : indique son nom.',
  levy_base_levy_unexpected: 'Cette mesure ne lit aucune autre règle.',
  levy_base_input_unexpected: 'Cette mesure ne lit aucun paramètre saisi.',
  base_levy_other_activity: 'Une règle ne lit que les règles de son activité.',
  base_levy_not_found: 'La règle lue n’existe plus.',
  base_levy_self: 'Une règle ne se lit pas elle-même.',
  levy_referenced: 'Une autre règle lit celle-ci : corrige-la d’abord, ou clos celle-ci.',
  levy_settlement_category_taken:
    'Une autre règle de cette activité règle déjà dans cette catégorie sur la même période : chacune compterait les paiements de l’autre. Donne-lui sa propre catégorie.',
  levy_has_settlements:
    'Un règlement a déjà été déclaré dans sa catégorie : cette règle fait partie de l’histoire. Clos-la.',
  supersede_before_start: 'Le remplacement commence après le début de la règle actuelle.',
  modifier_not_found: 'Ce modificateur n’existe plus.',
  modifier_needs_value: 'Cet effet a besoin d’une valeur.',
  modifier_value_invalid: 'La valeur du modificateur est hors de ses bornes.',
  modifier_single_duration: 'Un modificateur porte une seule durée : mois, périodes ou date de fin.',
  input_not_found: 'Ce paramètre n’existe plus.',
  input_value_invalid: 'Ce paramètre a besoin d’un nom et d’une valeur.',
  threshold_not_found: 'Ce seuil n’existe plus.',
  threshold_value_invalid: 'Un seuil a besoin d’un libellé, d’une valeur et de ce qui change au-delà.',
  bad_amount: 'Le montant doit être supérieur à zéro.',
  due_before_issue: 'L’échéance ne peut pas précéder l’émission.',
  withholding_exceeds_total: 'La retenue ne peut pas dépasser le total dû (HT + TVA).',
  invoice_not_found: 'Cette facture n’existe plus.',
  invoice_reference_taken: 'Une facture de cette activité porte déjà cette référence.',
  invoice_needs_income: 'Seul un revenu règle une facture.',
  invoice_other_client: 'Une facture est réglée par le client à qui elle a été émise.',
  invoice_other_activity: 'Le revenu qui règle une facture appartient à l’activité de la facture.',
  invoice_cancelled: 'Cette facture est annulée : rien n’est plus dû dessus.',
  invoice_currency_mismatch: 'Le revenu se déclare dans la devise de la facture.',
  invoice_overpaid: 'Ce montant dépasse le reste à recevoir sur la facture.',
  invoice_settled: 'Cette facture est déjà encaissée en entier.',
  invoice_has_payments: 'Des revenus règlent déjà cette facture : détache-les d’abord.',
  invoice_below_payments: 'Le net à recevoir ne peut pas passer sous ce qui a déjà été encaissé.',
  invoice_already_cancelled: 'Cette facture est déjà annulée.',
  invoice_not_open: 'Cette facture est encaissée ou annulée : rien à relancer.',
}
